# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

# Workaround for rsync on Windows issue
# https://github.com/mitchellh/vagrant/issues/3230#issuecomment-62588180
if ENV["VAGRANT_DETECTED_OS"].include? "MINGW"
  ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "chef"
  config.omnibus.chef_version = "11.16.2"

  config.vm.box = "opscode-centos-6.5"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443

  config.vm.provider :aws do |aws, override|
    override.vm.box = "redhat-6.5-x86_64-vagrant"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    aws.access_key_id = ENV["AWS_ACCESS_KEY"]
    aws.secret_access_key = ENV["AWS_SECRET_KEY"]
    aws.keypair_name = "mykey"
    aws.security_groups = ["sg-120cc877"]
    aws.subnet_id = "subnet-5796ae11"
    aws.instance_type = "m3.medium"
    aws.region = "us-west-1"
    aws.ami = "ami-f13826b4"
    aws.tags = {
      'Name' => config.vm.hostname + ' ' + Time.now.utc.iso8601,
      'Owner' => ENV['USER']
    }
    aws.elastic_ip = true
    aws.associate_public_ip = true
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "~/.ssh/mykey.pem"
  end

  config.vm.provision :chef_solo do |chef|
    chef.node_name = "chef"
    chef.cookbooks_path = "../../cookbooks"
    chef.data_bags_path = "../../data_bags"
    chef.encrypted_data_bag_secret_key_path = "../../insecure_data_bag_secret"

    chef.json = {
      "system" => {
        "short_hostname" => "chef",
        "domain_name" => "mycorp.com"
      }
    }

    chef.add_recipe "system"
    chef.add_recipe "mycorp-chef-server"
    chef.add_recipe "chef-server"

    chef.verbose_logging = true
    chef.log_level = :debug
  end
end
